import type {
  Template,
  CategoryItem,
  TemplateCategory,
  DocumentType,
  TargetEntity,
} from "@/types";

export const CATEGORIES: CategoryItem[] = [
  {
    id: "إدارة_الاجتماعات",
    label: "إدارة الاجتماعات",
    icon: "calendar",
    count: 4,
    color: "bg-blue-50 border-blue-200 text-blue-700",
  },
  {
    id: "المراسلات_الرسمية",
    label: "المراسلات الرسمية",
    icon: "mail",
    count: 4,
    color: "bg-teal-50 border-teal-200 text-teal-700",
  },
  {
    id: "اللوائح_والسياسات",
    label: "اللوائح والسياسات",
    icon: "file-text",
    count: 6,
    color: "bg-indigo-50 border-indigo-200 text-indigo-700",
  },
  {
    id: "التقارير_والإحصاء",
    label: "التقارير والإحصاء",
    icon: "bar-chart-2",
    count: 2,
    color: "bg-violet-50 border-violet-200 text-violet-700",
  },
  {
    id: "الشؤون_المالية",
    label: "الشؤون المالية",
    icon: "landmark",
    count: 2,
    color: "bg-emerald-50 border-emerald-200 text-emerald-700",
  },
  {
    id: "الموارد_البشرية",
    label: "الموارد البشرية",
    icon: "users",
    count: 4,
    color: "bg-sky-50 border-sky-200 text-sky-700",
  },
  {
    id: "الشراكات_والتعاون",
    label: "الشراكات والتعاون",
    icon: "handshake",
    count: 1,
    color: "bg-amber-50 border-amber-200 text-amber-700",
  },
  {
    id: "الشكر_والتقدير",
    label: "الشكر والتقدير",
    icon: "award",
    count: 2,
    color: "bg-rose-50 border-rose-200 text-rose-700",
  },
  {
    id: "البرامج_والمشاريع",
    label: "البرامج والمشاريع",
    icon: "folder-kanban",
    count: 6,
    color: "bg-orange-50 border-orange-200 text-orange-700",
  },
];

export const DOCUMENT_TYPES: { id: DocumentType | "all"; label: string }[] = [
  { id: "all", label: "جميع الأنواع" },
  { id: "محضر_اجتماع", label: "محضر اجتماع" },
  { id: "خطاب_رسمي", label: "خطاب رسمي" },
  { id: "لائحة_داخلية", label: "لائحة داخلية" },
  { id: "تقرير", label: "تقرير" },
  { id: "نموذج_تقديم", label: "نموذج تقديم" },
  { id: "عقد_وتفويض", label: "عقد وتفويض" },
  { id: "إعلان_ونشرة", label: "إعلان ونشرة" },
  { id: "شهادة_وتكريم", label: "شهادة وتكريم" },
];

export const TARGET_ENTITIES: { id: TargetEntity | "all"; label: string }[] = [
  { id: "all", label: "جميع الجهات" },
  { id: "وزارة_الموارد_البشرية", label: "وزارة الموارد البشرية" },
  { id: "المركز_الوطني_لتنمية_القطاع_غير_الربحي", label: "المركز الوطني لتنمية القطاع غير الربحي" },
  { id: "مجلس_الإدارة", label: "مجلس الإدارة" },
  { id: "الجمعية_العمومية", label: "الجمعية العمومية" },
  { id: "الجهات_التمويلية", label: "الجهات التمويلية" },
  { id: "الشركاء_والجهات_الأخرى", label: "الشركاء والجهات الأخرى" },
  { id: "داخلي", label: "للاستخدام الداخلي" },
];

export const TEMPLATES: Template[] = [
  {
    id: "tpl-001",
    title: "محضر اجتماع مجلس الإدارة",
    description:
      "نموذج احترافي لتوثيق اجتماعات مجلس الإدارة يشمل: قائمة الحضور، جدول الأعمال المرقّم، قرارات الاجتماع، الجهات المنفّذة، والمواعيد المحددة لكل قرار. مُعدّ وفق متطلبات المركز الوطني لتنمية القطاع غير الربحي والمنظمات الأهلية.",
    category: "إدارة_الاجتماعات",
    documentType: "محضر_اجتماع",
    targetEntity: "مجلس_الإدارة",
    tags: ["مجلس الإدارة", "قرارات", "توثيق", "حوكمة"],
    lastUpdated: "2026-07-15",
    downloads: 4820,
    rating: 4.8,
    isNew: false,
    isFeatured: true,
    relatedIds: ["tpl-002", "tpl-003", "tpl-015"],
    pageCount: 3,
    version: "2.1",
  },
  {
    id: "tpl-002",
    title: "محضر الجمعية العمومية العادية",
    description:
      "نموذج شامل لتوثيق اجتماعات الجمعية العمومية السنوية يتضمن: نصاب الانعقاد، مراجعة التقرير المالي، تقرير مراقب الحسابات، المصادقة على الميزانية، وانتخابات المجلس عند الاقتضاء.",
    category: "إدارة_الاجتماعات",
    documentType: "محضر_اجتماع",
    targetEntity: "الجمعية_العمومية",
    tags: ["جمعية عمومية", "انتخابات", "ميزانية", "سنوي"],
    lastUpdated: "2026-06-20",
    downloads: 3610,
    rating: 4.7,
    isNew: false,
    isFeatured: true,
    relatedIds: ["tpl-001", "tpl-005", "tpl-016"],
    pageCount: 5,
    version: "3.0",
  },
  {
    id: "tpl-003",
    title: "خطاب تعريف بالجمعية",
    description:
      "خطاب رسمي معتمد لتعريف الجمعية أمام الجهات الحكومية والقطاع الخاص والمانحين، يتضمن: البيانات الرسمية للترخيص، نطاق النشاط، والمنجزات الرئيسية.",
    category: "المراسلات_الرسمية",
    documentType: "خطاب_رسمي",
    targetEntity: "الشركاء_والجهات_الأخرى",
    tags: ["تعريف", "ترخيص", "رسمي", "مؤسسي"],
    lastUpdated: "2026-08-01",
    downloads: 6230,
    rating: 4.9,
    isNew: true,
    isFeatured: true,
    relatedIds: ["tpl-004", "tpl-007", "tpl-012"],
    pageCount: 2,
    version: "1.4",
  },
  {
    id: "tpl-004",
    title: "خطاب طلب دعم مالي من القطاع الخاص",
    description:
      "نموذج مهيكل لطلب الدعم المالي من الشركات والمؤسسات الخاصة، يتضمن: ملخص المشروع، الأثر المتوقع، الجدول الزمني، وآليات الإفصاح والشفافية.",
    category: "المراسلات_الرسمية",
    documentType: "خطاب_رسمي",
    targetEntity: "الجهات_التمويلية",
    tags: ["دعم", "تمويل", "قطاع خاص", "مسؤولية اجتماعية"],
    lastUpdated: "2026-05-10",
    downloads: 2890,
    rating: 4.6,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-003", "tpl-008", "tpl-017"],
    pageCount: 3,
    version: "2.0",
  },
  {
    id: "tpl-005",
    title: "اللائحة الداخلية للجمعية الأهلية",
    description:
      "مسودة لائحة داخلية متكاملة وفق أحدث اشتراطات وزارة الموارد البشرية، تشمل: أهداف الجمعية، شروط العضوية، صلاحيات مجلس الإدارة، اللجان الفرعية، النظام المالي، والفصل في النزاعات.",
    category: "اللوائح_والسياسات",
    documentType: "لائحة_داخلية",
    targetEntity: "وزارة_الموارد_البشرية",
    tags: ["لائحة", "تأسيس", "حوكمة", "وزارة"],
    lastUpdated: "2026-04-01",
    downloads: 5450,
    rating: 4.9,
    isNew: false,
    isFeatured: true,
    relatedIds: ["tpl-006", "tpl-002", "tpl-009"],
    pageCount: 18,
    version: "4.2",
  },
  {
    id: "tpl-006",
    title: "النظام الأساسي للجمعية",
    description:
      "النظام الأساسي التأسيسي للجمعية بصيغته القانونية الرسمية، يُقدَّم إلى الجهات الرسمية عند التسجيل والترخيص ويتوافق مع الأنظمة المُحدَّثة.",
    category: "اللوائح_والسياسات",
    documentType: "لائحة_داخلية",
    targetEntity: "المركز_الوطني_لتنمية_القطاع_غير_الربحي",
    tags: ["نظام أساسي", "تسجيل", "ترخيص", "قانوني"],
    lastUpdated: "2026-03-15",
    downloads: 3200,
    rating: 4.7,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-005", "tpl-002", "tpl-010"],
    pageCount: 12,
    version: "2.3",
  },
  {
    id: "tpl-007",
    title: "التقرير السنوي للجمعية",
    description:
      "قالب تقرير سنوي احترافي يشمل: رسالة رئيس مجلس الإدارة، ملخص الإنجازات، الأثر الميداني بالأرقام، التقرير المالي المختصر، وخطط العام القادم.",
    category: "التقارير_والإحصاء",
    documentType: "تقرير",
    targetEntity: "الجمعية_العمومية",
    tags: ["تقرير سنوي", "إنجازات", "مالية", "شفافية"],
    lastUpdated: "2026-07-30",
    downloads: 4100,
    rating: 4.8,
    isNew: true,
    isFeatured: true,
    relatedIds: ["tpl-008", "tpl-002", "tpl-013"],
    pageCount: 24,
    version: "1.6",
  },
  {
    id: "tpl-008",
    title: "تقرير المشروع للجهات التمويلية",
    description:
      "نموذج تقرير دوري مُوجَّه للمانحين والجهات التمويلية، يتضمن: نسبة التنفيذ، الصرف المالي مقابل الميزانية، المؤشرات الكمية، ومعوقات التنفيذ والحلول المقترحة.",
    category: "التقارير_والإحصاء",
    documentType: "تقرير",
    targetEntity: "الجهات_التمويلية",
    tags: ["تقرير", "مانحون", "مؤشرات", "تنفيذ"],
    lastUpdated: "2026-06-01",
    downloads: 2760,
    rating: 4.6,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-004", "tpl-007", "tpl-014"],
    pageCount: 8,
    version: "1.2",
  },
  {
    id: "tpl-009",
    title: "نموذج عقد العمل التطوعي",
    description:
      "اتفاقية تطوع رسمية تحدد التزامات المتطوع وحقوقه وواجباته، تشمل: ساعات التطوع، السرية، التأمين، وسياسة السلوك المهني.",
    category: "الموارد_البشرية",
    documentType: "عقد_وتفويض",
    targetEntity: "داخلي",
    tags: ["تطوع", "عقد", "متطوعون", "موارد بشرية"],
    lastUpdated: "2026-05-20",
    downloads: 3380,
    rating: 4.5,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-010", "tpl-011", "tpl-019"],
    pageCount: 4,
    version: "1.8",
  },
  {
    id: "tpl-010",
    title: "نموذج تفويض التوقيع",
    description:
      "صك تفويض رسمي يخوّل الموظف أو المسؤول التوقيع نيابةً عن الجمعية في معاملات محددة أمام الجهات الرسمية والبنوك والجهات الأخرى.",
    category: "الموارد_البشرية",
    documentType: "عقد_وتفويض",
    targetEntity: "داخلي",
    tags: ["تفويض", "توقيع", "صلاحيات", "رسمي"],
    lastUpdated: "2026-07-05",
    downloads: 1950,
    rating: 4.4,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-009", "tpl-006", "tpl-003"],
    pageCount: 2,
    version: "1.0",
  },
  {
    id: "tpl-011",
    title: "خطاب تزكية موظف",
    description:
      "نموذج خطاب تزكية رسمي لأعضاء فريق العمل والمتطوعين، يُقدَّم لجهات التوظيف أو البرامج التدريبية ويشمل تقييماً موضوعياً للمهارات والالتزام.",
    category: "الموارد_البشرية",
    documentType: "خطاب_رسمي",
    targetEntity: "الشركاء_والجهات_الأخرى",
    tags: ["تزكية", "توصية", "موظفون", "فريق"],
    lastUpdated: "2026-06-10",
    downloads: 1620,
    rating: 4.3,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-009", "tpl-010", "tpl-003"],
    pageCount: 1,
    version: "1.1",
  },
  {
    id: "tpl-012",
    title: "مذكرة تفاهم بين جمعيتين",
    description:
      "نموذج مذكرة تفاهم لتنظيم التعاون بين جمعيتين أهليتين في تنفيذ مشاريع مشتركة، يشمل: نطاق التعاون، الأدوار والمسؤوليات، الموارد، ومدة الاتفاقية.",
    category: "الشراكات_والتعاون",
    documentType: "عقد_وتفويض",
    targetEntity: "الشركاء_والجهات_الأخرى",
    tags: ["مذكرة تفاهم", "شراكة", "تعاون", "مشترك"],
    lastUpdated: "2026-07-20",
    downloads: 2140,
    rating: 4.6,
    isNew: true,
    isFeatured: false,
    relatedIds: ["tpl-013", "tpl-004", "tpl-003"],
    pageCount: 5,
    version: "2.0",
  },
  {
    id: "tpl-013",
    title: "خطاب دعوة لاجتماع تنسيقي",
    description:
      "نموذج دعوة رسمي لعقد اجتماع تنسيقي مع شركاء أو ممثلي القطاعات ذات الصلة، يتضمن: جدول الأعمال، مستلزمات الحضور، والتأكيدات المطلوبة.",
    category: "المراسلات_الرسمية",
    documentType: "خطاب_رسمي",
    targetEntity: "الشركاء_والجهات_الأخرى",
    tags: ["دعوة", "اجتماع", "تنسيق", "شركاء"],
    lastUpdated: "2026-08-05",
    downloads: 1830,
    rating: 4.4,
    isNew: true,
    isFeatured: false,
    relatedIds: ["tpl-001", "tpl-012", "tpl-007"],
    pageCount: 1,
    version: "1.0",
  },
  {
    id: "tpl-014",
    title: "الميزانية التقديرية السنوية",
    description:
      "نموذج ميزانية تقديرية سنوية متكامل للجمعيات الأهلية، يتضمن: بنود الإيرادات المتوقعة، المصروفات التشغيلية والبرامجية، الاحتياطيات، ومؤشرات الانحراف.",
    category: "الشؤون_المالية",
    documentType: "تقرير",
    targetEntity: "مجلس_الإدارة",
    tags: ["ميزانية", "مالية", "تخطيط", "إيرادات"],
    lastUpdated: "2026-01-10",
    downloads: 3670,
    rating: 4.7,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-015", "tpl-008", "tpl-007"],
    pageCount: 6,
    version: "2.4",
  },
  {
    id: "tpl-015",
    title: "قائمة الدخل والمركز المالي",
    description:
      "نماذج البيانات المالية الختامية للجمعيات وفق المعايير المحاسبية المعتمدة، تشمل: قائمة الدخل، قائمة المركز المالي، وإيضاحات البيانات.",
    category: "الشؤون_المالية",
    documentType: "تقرير",
    targetEntity: "الجمعية_العمومية",
    tags: ["بيانات مالية", "مركز مالي", "دخل", "محاسبة"],
    lastUpdated: "2026-02-28",
    downloads: 2980,
    rating: 4.8,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-014", "tpl-007", "tpl-002"],
    pageCount: 10,
    version: "3.1",
  },
  {
    id: "tpl-016",
    title: "نشرة الإعلان عن شاغر وظيفي",
    description:
      "نموذج إعلان وظيفي احترافي للجمعيات، يتضمن: وصف الوظيفة، المؤهلات المطلوبة، آلية التقديم، وبيانات التواصل.",
    category: "الموارد_البشرية",
    documentType: "إعلان_ونشرة",
    targetEntity: "داخلي",
    tags: ["وظيفة", "إعلان", "توظيف", "مؤهلات"],
    lastUpdated: "2026-07-25",
    downloads: 1240,
    rating: 4.3,
    isNew: true,
    isFeatured: false,
    relatedIds: ["tpl-009", "tpl-011", "tpl-010"],
    pageCount: 2,
    version: "1.0",
  },
  {
    id: "tpl-017",
    title: "شهادة مشاركة متطوع",
    description:
      "نموذج شهادة تقدير وإشادة لمتطوعي الجمعية تُصدر عقب انتهاء مدة التطوع، معتمدة بختم الجمعية وتوقيع المدير التنفيذي.",
    category: "الشكر_والتقدير",
    documentType: "شهادة_وتكريم",
    targetEntity: "داخلي",
    tags: ["شهادة", "متطوع", "تقدير", "إشادة"],
    lastUpdated: "2026-06-30",
    downloads: 2560,
    rating: 4.5,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-009", "tpl-018", "tpl-016"],
    pageCount: 1,
    version: "2.0",
  },
  {
    id: "tpl-018",
    title: "درع تكريم مؤسسي",
    description:
      "نموذج نص درع أو شهادة تكريم مؤسسية للشركاء والداعمين والشخصيات المؤثرة في عمل الجمعية.",
    category: "الشكر_والتقدير",
    documentType: "شهادة_وتكريم",
    targetEntity: "الشركاء_والجهات_الأخرى",
    tags: ["درع", "تكريم", "شكر", "شركاء"],
    lastUpdated: "2026-05-15",
    downloads: 1780,
    rating: 4.4,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-017", "tpl-003", "tpl-012"],
    pageCount: 1,
    version: "1.5",
  },
  {
    id: "tpl-019",
    title: "نموذج طلب عضوية في الجمعية",
    description:
      "استمارة طلب عضوية رسمية للراغبين في الانضمام إلى الجمعية، تتضمن البيانات الشخصية، المؤهلات، الاهتمامات، والموافقة على اللائحة الداخلية.",
    category: "اللوائح_والسياسات",
    documentType: "نموذج_تقديم",
    targetEntity: "داخلي",
    tags: ["عضوية", "تسجيل", "انضمام", "استمارة"],
    lastUpdated: "2026-07-10",
    downloads: 2870,
    rating: 4.5,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-005", "tpl-009", "tpl-006"],
    pageCount: 2,
    version: "1.3",
  },
  {
    id: "tpl-021",
    title: "محضر اجتماع طارئ لمجلس الإدارة",
    description:
      "نموذج محضر مُعدّ خصيصاً للاجتماعات الطارئة والعاجلة لمجلس الإدارة، يتضمن: مسوّغات الاجتماع وأسباب استدعائه، القرارات العاجلة المتخذة، آليات التنفيذ الفوري، ومتابعة المستجدات الطارئة. مُعدّ وفق متطلبات الحوكمة المؤسسية.",
    category: "إدارة_الاجتماعات",
    documentType: "محضر_اجتماع",
    targetEntity: "مجلس_الإدارة",
    tags: ["اجتماع طارئ", "مجلس الإدارة", "قرارات عاجلة", "حوكمة"],
    lastUpdated: "2026-08-15",
    downloads: 1840,
    rating: 4.6,
    isNew: true,
    isFeatured: false,
    relatedIds: ["tpl-001", "tpl-002", "tpl-003"],
    pageCount: 2,
    version: "1.0",
  },
  {
    id: "tpl-022",
    title: "محضر الجمعية العمومية غير العادية",
    description:
      "نموذج شامل لتوثيق اجتماعات الجمعية العمومية غير العادية (الاستثنائية)، يتضمن: أسباب الانعقاد غير العادي، النصاب القانوني الخاص، القرارات الجوهرية كتعديل اللائحة أو حل الجمعية أو الدمج، وإجراءات التصويت المُعززة.",
    category: "إدارة_الاجتماعات",
    documentType: "محضر_اجتماع",
    targetEntity: "الجمعية_العمومية",
    tags: ["جمعية عمومية", "غير عادية", "استثنائي", "تعديل لائحة"],
    lastUpdated: "2026-08-12",
    downloads: 1290,
    rating: 4.7,
    isNew: true,
    isFeatured: false,
    relatedIds: ["tpl-002", "tpl-005", "tpl-001"],
    pageCount: 4,
    version: "1.0",
  },
  {
    id: "tpl-023",
    title: "سياسة حماية البيانات الشخصية",
    description:
      "سياسة شاملة لحماية البيانات الشخصية للأعضاء والمستفيدين والعاملين، مُعدَّة وفق متطلبات نظام حماية البيانات الشخصية السعودي (PDPL). تتضمن: أنواع البيانات المُجمَّعة، آليات الجمع والمعالجة، حقوق أصحاب البيانات، الإجراءات الأمنية، وآلية الإبلاغ عن الانتهاكات.",
    category: "اللوائح_والسياسات",
    documentType: "لائحة_داخلية",
    targetEntity: "داخلي",
    tags: ["حماية البيانات", "PDPL", "خصوصية", "أمن المعلومات"],
    lastUpdated: "2026-08-18",
    downloads: 1870,
    rating: 4.8,
    isNew: true,
    isFeatured: true,
    relatedIds: ["tpl-005", "tpl-024", "tpl-025"],
    pageCount: 8,
    version: "1.0",
  },
  {
    id: "tpl-024",
    title: "لائحة المشتريات والتعاقدات",
    description:
      "لائحة تنظيمية متكاملة لضبط عمليات الشراء والتعاقد في الجمعية، تشمل: حدود الصلاحيات المالية، إجراءات طلب العروض وتقييمها، معايير اختيار الموردين، آليات إبرام العقود والإشراف على تنفيذها، وضوابط الصرف والمراجعة. مُعدَّة وفق أفضل ممارسات الحوكمة المؤسسية.",
    category: "اللوائح_والسياسات",
    documentType: "لائحة_داخلية",
    targetEntity: "مجلس_الإدارة",
    tags: ["مشتريات", "تعاقدات", "موردون", "حوكمة"],
    lastUpdated: "2026-08-15",
    downloads: 2340,
    rating: 4.7,
    isNew: true,
    isFeatured: false,
    relatedIds: ["tpl-005", "tpl-023", "tpl-014"],
    pageCount: 10,
    version: "1.0",
  },
  {
    id: "tpl-025",
    title: "سياسة تضارب المصالح",
    description:
      "وثيقة سياسة رسمية لمعالجة حالات تضارب المصالح الفعلية أو المحتملة لأعضاء مجلس الإدارة والعاملين والمتطوعين. تتضمن: تعريف تضارب المصالح، الإفصاح المطلوب، آلية التنحي عن القرارات، سجل الإفصاح السنوي، والعقوبات المترتبة على المخالفة. أساس لبناء بيئة مؤسسية نزيهة وشفافة.",
    category: "اللوائح_والسياسات",
    documentType: "لائحة_داخلية",
    targetEntity: "مجلس_الإدارة",
    tags: ["تضارب المصالح", "نزاهة", "شفافية", "حوكمة"],
    lastUpdated: "2026-08-20",
    downloads: 1560,
    rating: 4.9,
    isNew: true,
    isFeatured: false,
    relatedIds: ["tpl-005", "tpl-006", "tpl-023"],
    pageCount: 5,
    version: "1.0",
  },
  {
    id: "tpl-020",
    title: "خطاب رد على استفسار رسمي",
    description:
      "نموذج خطاب رد رسمي ومهيكل على الاستفسارات الواردة من الجهات الرسمية أو الشركاء، يُبرز الاحترافية ويوثّق الموقف الرسمي للجمعية.",
    category: "المراسلات_الرسمية",
    documentType: "خطاب_رسمي",
    targetEntity: "وزارة_الموارد_البشرية",
    tags: ["رد", "استفسار", "رسمي", "مراسلات"],
    lastUpdated: "2026-08-10",
    downloads: 1460,
    rating: 4.4,
    isNew: true,
    isFeatured: false,
    relatedIds: ["tpl-003", "tpl-013", "tpl-004"],
    pageCount: 2,
    version: "1.0",
  },
  // ── البرامج والمشاريع ──
  {
    id: "tpl-101",
    title: "وثيقة تأسيس المشروع (Project Charter)",
    description:
      "وثيقة رسمية لإطلاق المشروع تتضمن: الأهداف الاستراتيجية، نطاق العمل، الجدول الزمني الرئيسي، الميزانية الإجمالية، المخاطر المتوقعة، والجهات المعنية. تُشكّل المرجع الأساسي للمشروع طوال دورة حياته.",
    category: "البرامج_والمشاريع",
    documentType: "نموذج_تقديم",
    targetEntity: "مجلس_الإدارة",
    tags: ["تأسيس مشروع", "تخطيط", "أهداف", "نطاق"],
    lastUpdated: "2026-08-01",
    downloads: 2140,
    rating: 4.8,
    isNew: true,
    isFeatured: true,
    relatedIds: ["tpl-102", "tpl-103", "tpl-008"],
    pageCount: 5,
    version: "1.0",
  },
  {
    id: "tpl-102",
    title: "خطة العمل التفصيلية للمشروع",
    description:
      "جدول تنفيذي مفصّل للمشروع يشمل: المخرجات والأنشطة المرحلية، المسؤوليات، الجدول الزمني (مخطط غانت)، والموارد المخصصة لكل نشاط. يُستخدم كأداة متابعة يومية لفريق التنفيذ.",
    category: "البرامج_والمشاريع",
    documentType: "تقرير",
    targetEntity: "داخلي",
    tags: ["خطة عمل", "جدول زمني", "أنشطة", "مخرجات"],
    lastUpdated: "2026-07-20",
    downloads: 3280,
    rating: 4.7,
    isNew: false,
    isFeatured: true,
    relatedIds: ["tpl-101", "tpl-103", "tpl-104"],
    pageCount: 8,
    version: "2.1",
  },
  {
    id: "tpl-103",
    title: "نموذج تقديم طلب تمويل مشروع",
    description:
      "استمارة احترافية لتقديم طلب تمويل للجهات المانحة والصناديق الحكومية، تتضمن: ملخصاً تنفيذياً، تحليل المشكلة، المنهجية، الفئة المستهدفة، الميزانية التفصيلية، ومؤشرات الأثر والاستدامة.",
    category: "البرامج_والمشاريع",
    documentType: "نموذج_تقديم",
    targetEntity: "الجهات_التمويلية",
    tags: ["تمويل", "طلب منحة", "مانحون", "استدامة"],
    lastUpdated: "2026-06-15",
    downloads: 4650,
    rating: 4.9,
    isNew: false,
    isFeatured: true,
    relatedIds: ["tpl-101", "tpl-104", "tpl-004"],
    pageCount: 12,
    version: "3.0",
  },
  {
    id: "tpl-104",
    title: "تقرير المتابعة والرصد الميداني",
    description:
      "نموذج تقرير متابعة دوري لرصد تقدم المشروع ميدانياً، يشمل: مؤشرات الأداء الرئيسية (KPIs)، نسب الإنجاز مقارنةً بالمخطط، المستفيدين المُخدَّمين، الانحرافات، والتوصيات التصحيحية.",
    category: "البرامج_والمشاريع",
    documentType: "تقرير",
    targetEntity: "مجلس_الإدارة",
    tags: ["متابعة", "رصد", "مؤشرات أداء", "ميداني"],
    lastUpdated: "2026-08-10",
    downloads: 2890,
    rating: 4.6,
    isNew: true,
    isFeatured: false,
    relatedIds: ["tpl-102", "tpl-105", "tpl-008"],
    pageCount: 6,
    version: "1.4",
  },
  {
    id: "tpl-105",
    title: "التقرير الختامي للمشروع",
    description:
      "تقرير إغلاق شامل يوثّق نتائج المشروع النهائية مقارنةً بالأهداف، يتضمن: الدروس المستفادة، التوصيات المستقبلية، الأثر الفعلي على المستفيدين، والوضع المالي النهائي. يُقدَّم للممولين ومجلس الإدارة.",
    category: "البرامج_والمشاريع",
    documentType: "تقرير",
    targetEntity: "الجهات_التمويلية",
    tags: ["تقرير ختامي", "إغلاق", "دروس مستفادة", "أثر"],
    lastUpdated: "2026-07-05",
    downloads: 3120,
    rating: 4.8,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-104", "tpl-007", "tpl-103"],
    pageCount: 15,
    version: "2.0",
  },
  {
    id: "tpl-106",
    title: "استبيان قياس رضا المستفيدين",
    description:
      "نموذج استبيان احترافي لقياس مستوى رضا المستفيدين عن برامج وخدمات الجمعية، يشمل: محاور الجودة والملاءمة والأثر، مع مقياس ليكرت الخماسي وأسئلة مفتوحة للاقتراحات.",
    category: "البرامج_والمشاريع",
    documentType: "نموذج_تقديم",
    targetEntity: "داخلي",
    tags: ["استبيان", "رضا المستفيدين", "تقييم", "جودة"],
    lastUpdated: "2026-06-20",
    downloads: 2430,
    rating: 4.5,
    isNew: false,
    isFeatured: false,
    relatedIds: ["tpl-104", "tpl-105", "tpl-007"],
    pageCount: 3,
    version: "1.2",
  },
];

export const SUGGESTED_KEYWORDS = [
  "محضر اجتماع",
  "خطاب تعريف",
  "لائحة داخلية",
  "تقرير سنوي",
  "عقد تطوع",
  "ميزانية تقديرية",
  "مذكرة تفاهم",
  "شهادة تقدير",
];

export const STATS = {
  templates: 31,
  downloads: 200,
  associations: 100,
};
